# Generated by Django 5.2.12 on 2026-03-26 05:38

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('vote_cast', 'Vote cast'), ('vote_edited', 'Vote edited'), ('question_opened', 'Question opened'), ('question_closed', 'Question closed'), ('user_login', 'User login')], max_length=32)),
                ('actor', encrypted_model_fields.fields.EncryptedCharField()),
                ('payload', encrypted_model_fields.fields.EncryptedCharField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Audit entry',
                'verbose_name_plural': 'Audit entries',
                'ordering': ['timestamp'],
            },
        ),
    ]
