# Generated by Django 5.2.12 on 2026-03-26 05:38

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the assembly.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the assembly.', verbose_name='Description')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled at')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the decision option set', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of the decision option set.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Decision option set',
                'verbose_name_plural': 'Decision option sets',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the agenda item.', max_length=255, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the agenda item.', verbose_name='Order')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='assemblies.assembly')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='label for this option', max_length=255, verbose_name='Label')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the option', verbose_name='Order')),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assemblies.decisionoptionset')),
            ],
            options={
                'verbose_name': 'Decision option',
                'verbose_name_plural': 'Decision options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', encrypted_model_fields.fields.EncryptedCharField(help_text='Question text.', verbose_name='Text')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the question.', verbose_name='Order')),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('open', 'Opened'), ('closed', 'Closed')], default='pending', help_text='Status of the question.', max_length=10, verbose_name='Status')),
                ('opened_at', models.DateTimeField(blank=True, help_text='When this question was opened.', null=True, verbose_name='Opened')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When this question was closed.', null=True, verbose_name='Closed')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assemblies.agenda')),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assemblies.decisionoptionset')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='When this attendance was registered.', verbose_name='Registered at')),
                ('registered_by_admin', models.BooleanField(default=False, help_text='Whether this attendance was registered by an admin.', verbose_name='Was it registered by an admin?')),
                ('by_proxy', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='assemblies.question')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'unique_together': {('question', 'member')},
            },
        ),
    ]
