# Generated by Django 5.2.12 on 2026-03-27 18:48

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Question helper.', null=True, verbose_name='Text'),
        ),
    ]
