# Generated by Django 5.2.12 on 2026-03-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0002_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionoptionset',
            name='abstention_option',
            field=models.OneToOneField(blank=True, help_text='The option that represents abstention and will be excluded from percentage calculations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assemblies.decisionoption', verbose_name='Abstention option'),
        ),
    ]
