# Generated by Django 5.2.12 on 2026-03-26 05:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Your name', verbose_name='Name')),
                ('email', encrypted_model_fields.fields.EncryptedEmailField(blank=True, help_text='Your email address. e.g.: email@email.com', verbose_name='Email address')),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Your telephone number, with DDD or DDI', verbose_name='Telephone number')),
                ('address', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Your address for correspondences. e.g.: Avenida Paulista, 2278, andar Pilotis - Bela Vista', verbose_name='Address')),
                ('city', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='The city you are residing. e.g.: São Paulo', verbose_name='City')),
                ('state', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='The state you are residing. e.g.: São Paulo', verbose_name='State')),
                ('postal_code', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='The postal code of your address. e.g.:01.310-300', verbose_name='Postal code')),
                ('country', encrypted_model_fields.fields.EncryptedCharField(default='Brasil', help_text='The country you are residing. e.g.: Brazil', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
