# Generated by Django 5.2.12 on 2026-03-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='assemblies.assembly')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies_received', to='members.member')),
                ('grantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies_granted', to='members.member')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
                'unique_together': {('assembly', 'grantee'), ('assembly', 'grantor')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('on_behalf_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='members.member')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='assemblies.decisionoption')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='voting.proxy')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='assemblies.question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='members.member')),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
                'unique_together': {('question', 'on_behalf_of')},
            },
        ),
    ]
